### ISSUE TITLE
Memory usage DownloadButton

### ISSUE THREAD

**Issue by willemvd** [opencirclesolutions/dynamo#103]
The DownloadButton always expects that the content is delivered as byte[] 
This can cause memory issues when large files are downloaded
Changing the com.ocs.dynamo.ui.component.DownloadButton#doCreateContent to return an InputStream, and make the whole flow stream based, can fix this (implementations can still do in memory stuff with java.io.ByteArrayInputStream#ByteArrayInputStream(byte[]) )

**Comment by wittekip** [comment]
Merged this from customer development branch to v12 branch
