### ISSUE TITLE
Feature #98: proper internationalization for textual entity model properties

### ISSUE THREAD

**Issue by wittekip** [opencirclesolutions/dynamo#119]
It is currently not possible to adapt the various textual entity model properties (displayName, displayNamePlural etc) based on the locale of the user that is logged in. 

To be able to do so, we would need to replace the property's like "displayName" by a map that maps from locale identifier to desired value in that locale, and then scan the classpath for all provided resource bundles that contain translations and add them to the map during entity model construction

**Comment by pdeenen** [comment]
Is this not possible using resource bundles for the property overrides for each translated locale?

**Comment by wittekip** [comment]
It is possible and even necessary to use resource bundles for different locales, but that by itself is not enough. The entity model is a singleton, only one instance is created across the entire application and as such it is based on just one locale - you need some additional work (as outlined above) to be able to adapt to the locale of the individual user that is logged in
