### ISSUE TITLE
Figure out how to change the number of rows in a grid

### ISSUE THREAD

**Issue by wittekip** [opencirclesolutions/dynamo#138]
In the previous version of Dynamo, it was possible to set the number of rows for a table by using the setPageLength method. This no longer seems to work for a Grid (method does not exists) and it is not obvious how do this in Vaadin 8. Investigate and make sure that we can once again set the number of rows to display for a table

**Comment by jweijers** [comment]
For now expose the layout from the gridWrapper, this allows full control over the size of the grid and does enable scrollbars when needed.
