### ISSUE TITLE
Remove all references to java.util.Date and java.sql.Date from Dynamo

### ISSUE THREAD

**Issue by wittekip** [opencirclesolutions/dynamo#147]
With the new version of Dynamo, it is no longer useful to support java.util.Date and java.sql.Date. The Vaadin 8 -based frontend no longer supports these legacy types so it makes no sense to use them in the backend

**Comment by jweijers** [comment]
A few more are left in the excel import/export function. Current version of Apache POI doesn't understand java.time package so these will have to wait for an upgrade of apache POI.

**Comment by wittekip** [comment]
There are also some references left in the DateUtils and in some of the Vaadin converters - can you try to remove some of these as well?

**Comment by jweijers** [comment]
They are gone. All that remains is in comments because not reenabled or Excel import/export I propose to deal with these java.util.Date instances when upgrading these parts

**Comment by wittekip** [comment]
OK, can we close this ticket then?
