### ISSUE TITLE
Feature 9: Add Maven Archetype

### ISSUE THREAD

**Issue by OpenCircleEndy** [opencirclesolutions/dynamo#21]

**Comment by wittekip** [comment]
I've taken a look at a project generated by the current archetype and I think the current archetype is far too limited - it generates a project that consists of just one subproject and does not follow the application architecture described in the manual (and showcased by Roomplanner and SAS) at all.

**Comment by OpenCircleEndy** [comment]
Agreed to add another archetype with these feature.
