### ISSUE TITLE
Quick detail view has no tooltip

### ISSUE THREAD

**Issue by pdeenen** [opencirclesolutions/dynamo#225]
See GTS 4.0 when hovering over the quick detail view action button in the organisation result table.
Other framework actions like the delete button are also missing a tooltip.

**Comment by wittekip** [comment]
Added tooltips to:
- Delete button, Detail screen button, and popup button in table
- Delete button in flexible search layout

Note that no tooltips were added to buttons that already contain text explaining what they do.
