### ISSUE TITLE
Merge documentation and training in one module

### ISSUE THREAD

**Issue by tommy-ocs** [opencirclesolutions/dynamo#266]
Currently, the main Dynamo documentation and the Dynamo training documentation are located in two separate modules. I suggest to merge these. This way, it is also easier to release the documentation together on the [Dynamo site](https://dynamoframework.org).

**Comment by wittekip** [comment]
This was done more or less on purpose in order not to create confusion with the image directory that both the training and the documentation document need. It's no super big deal but I'd just leave it as is

**Comment by tommy-ocs** [comment]
See #237
