### ISSUE TITLE
Feature 13: Spinners for integers/long

### ISSUE THREAD

**Issue by wittekip** [opencirclesolutions/dynamo#28]
When generating a form, Dynamo now generates a text field for  editing a property of type Integer (or Long).

I would propose adding functionality that makes it possible to configure that a spinner field should be used instead

**Comment by jweijers** [comment]
Still todo property based spinners/sliders

**Comment by wittekip** [comment]
Added functionality for Sliders now - we will not add support for Spinners at the moment due to lack of proper component
