### ISSUE TITLE
Feature 21: Implement Edit Mode in TabularEditLayout

### ISSUE THREAD

**Issue by OpenCircleEndy** [opencirclesolutions/dynamo#38]
This is not implemented in the TabularEditLayout. This prevents the Show Case to compile. The following code is added: 

`protected void detailsMode(T entity) {
        // TODO Make the Show Case Compile.
}`

**Comment by wittekip** [comment]
Simply adding this method is enough, the TabularEditLayout already support an edit mode (you can edit directly in the table) and doesn't need to implement this method

**Comment by wittekip** [comment]
No further action needed on this - works as intended now
