### ISSUE TITLE
Feature 60: Refactor maven project structure

### ISSUE THREAD

**Issue by pdeenen** [opencirclesolutions/dynamo#49]
To new maven project structure:
- dynamo-common - utility and other reusable classes
- dynamo-api - Only interfaces for the (entity) model, DAO api, NO JPA dependencies, including the common (entity model implementations)
- dynamo-dao-jpa - The JPA dao implementation
- dynamo-service - Both API and default service implementations
- dynamo-ui-vaadin - Common Vaadin UI components without JPA dependencies
- dynamo-ui-vaadin-jpa - The JPA Vaadin Entity model factory implementation
- dynamo-camel - All common camel integration components
- dyname-jee - JEE specific configuration
- dynamo-spring - Spring specific configuration

**Comment by wittekip** [comment]
Project structure was refactored into an acceptable alternative a while back. I am closing this.
