### ISSUE TITLE
Feature 50: System wide defaults

### ISSUE THREAD

**Issue by willemvd** [opencirclesolutions/dynamo#58]
Add system/application wide defaults for the following attributes:
- TrueRepresentation
- FalseRepresentation
- searchCaseSensitive
- searchPrefixOnly

**Comment by wittekip** [comment]
This involves adding system properties and methods on the SystemPropertyUtils to read from it. Then, in the EntityModelFactoryImpl, read the appropriate system property values and set them as default values on the AttributeModelImpl
