### ISSUE TITLE
Feature 52: Capitalization strategy

### ISSUE THREAD

**Issue by willemvd** [opencirclesolutions/dynamo#60]
Default strategy (from Vaadin) for displaying the displayName is to uppercase each word, for example: 
member: minimumAge 
default behaviour: Minimum Age

Create a strategy to set this to another default, for example to create: Minimum age

**Comment by OpenCircleEndy** [comment]
The `com.ocs.dynamo.domain.model.annotation.Attribute` already contains a property for setting the display name. My interpretation is to configure another standard, default, way for displaying javabean properties when no display name is set for the attribute.

**Comment by OpenCircleEndy** [comment]
Added a system property 'ocs.default.caption.format' which controls the capitalization. Setting a value anything other than 'vaadin' will make the capitalization use lower case words after the first one.
