### ISSUE TITLE
Feature 55: Adding custom code before searching.

### ISSUE THREAD

**Issue by OpenCircleEndy** [opencirclesolutions/dynamo#75]
Add or implement a callback that is executed before a search is performed. This allows additional code to be executed before sending the search request. Typical use cases would be a complex search form validation or adding additional pre-search conversions.

**Comment by wittekip** [comment]
There is now the "beforeSearchPerformed" method which can be used to intercept the control flow before a search is carried out - this can be modified to modify the search filter. Need to investigate a bit more if this is also suitable for e.g. aborting the search if a condition is not met

**Comment by wittekip** [comment]
Added a new "validateBeforeSearch" callback method that can be used to perform custom validations before searching
