### ISSUE TITLE
Fix tokenfield to prevent the duplicate selection

### ISSUE THREAD

**Issue by pdeenen** [opencirclesolutions/dynamo#84]
Currently the selection list in the tokenfield will always show the same list, hence it is possible to make an selection of an item that already is selected. As the tokenfield currently not support dublicate selections, it should not show items in the selection list that are already selected.

**Comment by wittekip** [comment]
As far as I know, an item does still show up in the selection list after you have already selected it, but it won't actually be added again to the selected items if you end up selecting it again. So the current way this works doesn't really break anything

**Comment by wittekip** [comment]
Token field has been replaced by newer and better version, therefore this can be closed.
