### ISSUE TITLE
Details not shown in a SimpleSearchLayout after double click on row

### ISSUE THREAD

**Issue by Airrudi** [opencirclesolutions/dynamo#87]
When double clicking a row in the SimpleSearchLayout, no detail view is shown.
The settings for the formoptions:

`FormOptions fo = new formOptions().setOpenInViewMode(true).setShowEditButton(true).setReadOnly(true);
`

**Comment by wittekip** [comment]
Fixed in cm1branch-v13; will soon migrate to master
