### ISSUE TITLE
Feature #87: Add support for REST services

### ISSUE THREAD

**Issue by wittekip** [opencirclesolutions/dynamo#88]

**Comment by pdeenen** [comment]
There are several solutions thinkable for this feature:

1. Use [Odata](http://www.odata.org/) as REST API by implementing a generic service wrapper around our Dynamo service interface using [Apache Olingo](https://olingo.apache.org/doc/odata4/index.html).
2. Use [GraphQL](http://graphql.org/) as REST API by implementing a generic service wrapper around our Dynamo service interface using [Apache Olingo](https://olingo.apache.org/doc/odata4/index.html).

**Comment by jweijers** [comment]
As a framework http://sparkjava.com might also be considered.

Benefits
Flexible
Small framework

Drawbacks
Just rest no standards
Long term support?
