### ISSUE TITLE
ReportGenerator is not thread safe

### ISSUE THREAD

**Issue by wittekip** [opencirclesolutions/dynamo#97]
The ReportGenerator class from dynamo-jasperreports is defined as a singleton scoped service, however it contains state (the "margin" field). This makes it non-threadsafe when multiple clients call the setMargin method followed by the "export" methods. 

I suggest removing the "margin" property and implementing it as a method parameter instead

**Comment by willemvd** [comment]
This is already applied on branch cm1branch-v14 as part of commit https://github.com/opencirclesolutions/dynamo/commit/d24ab87035a153b762afffe3b22a98fbc2ec10cc

**Comment by wittekip** [comment]
Closing this for now - will have to be looked at again as part of the migration of all the JasperReports changes from cm1branch-v14 to v12
